### ISSUE TITLE
Lolcat Forces Cursor to be Visible

### ISSUE THREAD

**Issue by applesud** [busyloop/lolcat#122]
**Expected Behaviour:**
Lolcat doesn't affect cursor visibility.

**Actual Behaviour:**
Lolcat makes cursor visible.

**Example:**
```bash
$ tput  civis  # makes cursor invisible
$ echo "hello" | lolcat  # makes cursor visible (it shouldn't)
```

**Causes:**
This seems to be the relevant line of code:
https://github.com/busyloop/lolcat/blob/b7ce4bd8882d22ee3db4b7d4d0df43eab6851cf5/lib/lolcat/lol.rb#L64

**Comment by m-o-e** [comment]
There is unfortunately no good way to fix this because there's (afaik)
no way to detect the status of cursor visibility.

Lolcat hides the cursor to avoid flickering and then
enables it again, because that's the desired behavior most
of the time and it can't know what the original state was.

If you wish to hide the cursor after invoking lolcat
you can follow it up with:
`echo -e '\e[?25l'`
