### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by robertocarlosmedina** [busyloop/lolcat#127]
How did you add your program to be instal like this "$ sudo apt install lolcat"
waiting for answers

**Comment by acoolstraw** [comment]
The package has to have an [apt](https://en.wikipedia.org/wiki/APT_(software)) repository, and it actually does on Debian Bullseye (I'm not sure if it's latest). If you have Ubuntu, you most likely can run `sudo snap install lolcat` instead of installing with `apt`.
![image](https://user-images.githubusercontent.com/45886986/140634195-91dbc2b3-2802-455b-bff1-32024a2dec30.png)

**Comment by robertocarlosmedina** [comment]
My question was how do i put my own package to be available for Ubuntu users, to  be downloaded by sudo snap install lolcat for examples.

**Comment by acoolstraw** [comment]
This isn't the place to ask that, there are plenty of guides on the internet on how to release a package for snap, apt, AUR, etc.
