### ISSUE TITLE
Can't pipe infinite data to lolcat

### ISSUE THREAD

**Issue by tyilo** [busyloop/lolcat#25]
With `cat` you can do this to get boring infinite white text:

```
cat /dev/random | base64 | cat
```

However, when doing the same with `lolcat`, it never shows any awesome rainbow colored output:

```
cat /dev/random | base64 | lolcat
```

**Comment by p-s-** [comment]
I havethe same problem, 

> cat /dev/urandom | base64 | lolcat

 doesn't work for me, no output.

This issue is closed, i just found it because I'm having troubles running another program in terminal, and getting awesome rainbow colored output while piping it through lolcat ...

why does it work for you, @m-o-e ?
Are there settings in terminal I have to adjust?!

**Comment by m-o-e** [comment]
There are certain versions of `base64` that buffer all input before doing anything.

Does this one work for you: `cat /dev/urandom | hexdump | lolcat` ?

**Comment by p-s-** [comment]
thank you for helping a newbie @m-o-e : )
this one works for me!

So I guess https://github.com/houeland/kolproxy from @houeland doesn't give me live-lolcat greatness, because of its "buffer design"?! It's a shame 🙈
