### ISSUE TITLE
Installation on OS X El Capitan

### ISSUE THREAD

**Issue by romulof** [busyloop/lolcat#37]
The installation fails when trying to symlink to `/usr/bin`.

Fix: change to `/usr/local/bin`

**Comment by m-o-e** [comment]
Ruby gems have no control over their installation paths.
The destination for executables is platform specific and usually (like on OSX) defaults to `/usr/bin`.

Please use `sudo gem install lolcat` to perform the installation.

**Comment by m-o-e** [comment]
Interesting.

I don't have El Capitan to test, could you check if this problem also applies to other gems (for example: `gem install t`).

If other gems don't have this problem then I'll look into how they get around it.
If they have the same problem then I'm afraid El Capitan ships with a broken Ruby installation.

**Comment by romulof** [comment]
Yes, it shows the same error.

**Comment by m-o-e** [comment]
Sorry, your best bet from here is to use a sandboxed Ruby ([rbenv](https://github.com/sstephenson/rbenv) or [rvm](https://rvm.io/)).

A Ruby installed via [homebrew](http://brew.sh/) _probably_ also works
around the problem, but I haven't tested that personally.

Let's hope Apple fixes this before the release of El Capitan.

**Comment by romulof** [comment]
It didn't produced error, but the binary was not symlinked to PATH:
Install location: `~/.gem/ruby/2.0.0/bin/lolcat`

**Comment by m-o-e** [comment]
I was told this should be fixed in the latest El Capitan beta (10.11 dev beta).
Would be cool if you can confirm when you get a chance to upgrade.

**Comment by romulof** [comment]
Ok, I'll keep this updated.

BTW: It's not the first time an OS X beta messes with Ruby. :/

**Comment by Boggartfly** [comment]
You will have to disable system integrity protection from the recovery partition, and then remove the system flag restricted via
```
sudo chflags -R norestricted /usr/local/
```
This will recursively remove the restricted flag and make that partition writable after disabling system integrity protection. Also I don't know whether this works without disabling the system integrity protection from the recovery partition.
This issue often happens if you install and then reinstall brew on the same machine running el capitan.
I currently have Version 10.11 Beta (15A243d).

**Comment by m-o-e** [comment]
Closing this now since it's an OSX bug, not a lolcat bug.
Thanks to everybody who contributed!
