### ISSUE TITLE
/usr/lib/ruby/gems/2.6.0/gems/lolcat-99.9.11/lib/lolcat/lol.rb:63: warning: Insecure world writable dir /home/elswerky/.local in PATH, mode 040777

### ISSUE THREAD

**Issue by elswerky** [busyloop/lolcat#85]
i get this line at the end of output every time i run lolcat  on arch on  **_wsl_**
** /usr/lib/ruby/gems/2.6.0/gems/lolcat-99.9.11/lib/lolcat/lol.rb:63: warning: Insecure world writable dir /home/elswerky/.local in PATH, mode 040777**

any idea how to fix it ??

**Comment by elswerky** [comment]
i removed ~/.local folder and now i get a new error 

/usr/lib/ruby/gems/2.6.0/gems/lolcat-99.9.11/lib/lolcat/lol.rb:63: warning: Insecure world writable dir /mnt/c in PATH, mode 040777


is there any way to hide or disable this warning ??

**Comment by m-o-e** [comment]
@elswerky
This is not a lolcat-specific message but a lower level security warning.

Your `PATH`-variable contains a world-writable directory (`/mnt/c`).
This variable tells your shell where to search for executables when you type a command.

Having a world-writable directory in there is a bad idea.
It means any user on your system could, for example, put a script called `ls`
there - and the next time you try to list a directory you might execute this
script instead of the actual `/bin/ls` binary.

I would suggest to remove this directory from your `PATH`
or to change the permissions so that it is not world-writable anymore.

**Comment by elswerky** [comment]
> @elswerky
> This is not a lolcat-specific message but a lower level security warning.
can you tell me how to remove it from path permently ?? 
elswerky tmp $ echo $PATH
/home/elswerky/bin:/home/elswerky/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/mahmo/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mahmo/AppData/Local/Programs/Fiddler

how to remove such path permently ( i mean windows dirs in $PATH)

**Comment by m-o-e** [comment]
Sorry, I'm not familiar with Windows, so I don't know.

Possibly this thread (found with a quick google) might lead to a workaround:
https://github.com/Microsoft/WSL/issues/2476

**Comment by elswerky** [comment]
> Sorry, I'm not familiar with Windows, so I don't know.
> 
> Possibly this thread (found with a quick google) might lead to a workaround:
> [Microsoft/WSL#2476](https://github.com/Microsoft/WSL/issues/2476)

they are paths in linux bash on wsl 
so the way to remove them is just like in any linux distro ,,i will google it to see how to remove paths in linux permently 
Thanks
