### ISSUE TITLE
colors rotation breaks at line 47

### ISSUE THREAD

**Issue by l3nn4rt** [busyloop/lolcat#96]
```
head -n 100 /dev/urandom | tr -cd '[:alnum:]' | fold | cat -n | lolcat
```
![image](https://user-images.githubusercontent.com/20030650/60018878-bb17d580-968c-11e9-9251-379f94235624.png)

**Comment by m-o-e** [comment]
The same command prints fine here. What version of lolcat do you have?

Does the problem also occur with `head -n 100 /dev/urandom | base64 | head -n 70 | lolcat`?

**Comment by l3nn4rt** [comment]
version is `lolcat 99.9.21 (c)2011 moe@busyloop.net`.

happens also with that command, but is less visible:
![image](https://user-images.githubusercontent.com/20030650/60034761-98e18000-96ab-11e9-8443-36b4a0fc22f1.png)

**Comment by m-o-e** [comment]
Sorry, can't reproduce this here.
Weird wraps in the color cycle are normally due to unintended line-breaks, but
that doesn't seem to be the case here (still space left on the right of your screenshot).

Things you could try:

* Different terminal emulator
* Installing lolcat from rubygems (`gem install lolcat`) instead of using a packaged version

**Comment by l3nn4rt** [comment]
still happening with:
- all  `(terminal, shell)` in `{gnome-terminal, tilix, terminator} x {zsh,bash}`,
- package (ver. 99.9.69) from rubygems

I won't dive deeper into this. leaving open just in case anyone experiments the same "feature" :smile:

**Comment by m-o-e** [comment]
Bug found and buried.
Latest lolcat should restore satisfaction 🌈
